on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: IbzanHyena/setup-j@v1
        with:
          j-version: "903"
      - run: |
          ijconsole test.ijs

